import './globals.css'
import { Inter } from 'next/font/google'

import LoginBeforeNavBar from './components/login-before-navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'secure login',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <LoginBeforeNavBar />
        {children}
      </body>
    </html>
  )
}
